#!/bin/bash

# This script dumps the bandwidth stats to files
# which are then processed by netuse script.

# crontab entry:
# */10 * * * * /path/to/dumper

read -r date month year <<< "$(date +'%d %b %G')"

# Make sure the directories exist
mkdir -p "$HOME/.net/$year/$month/"{down,up}

# I use an MTS MBlaze Dongle - www.mtsindia.in/mblaze/
# which registers itself as a ppp device.
printf "%s;%s\n" "$(< /sys/class/net/ppp0/statistics/rx_bytes)" "$(date +%s)" >> "$HOME/.net/$year/$month/down/$date"
printf "%s;%s\n" "$(< /sys/class/net/ppp0/statistics/tx_bytes)" "$(date +%s)" >> "$HOME/.net/$year/$month/up/$date"
